### ISSUE TITLE
Tags management > Tag with transactions cannot be assigned to a user when it has anonymous sessions

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1832] opened 2020-10-15 10:37 UTC
It can also not be deleted.

**Comment by LucasBrazi06** [comment] 2020-10-15 11:19
Normal behavior. Not an issue.

**Comment by LucasBrazi06** [comment] 2020-10-15 11:43
@mahdibenromdhane 
We need just to check only the sessions with userID is provided (not null).
So just refine the MongoDB request if it's not done yet.

**Comment by jerome-benoit** [comment] 2020-10-15 12:07
> Normal behavior. Not an issue.

Tag in badges in companies are reused. So tags must be able to change owner.

**Comment by LucasBrazi06** [comment] 2020-10-15 12:12
> Tag in badges in companies are reused. So tags must be able to change owner.

This is not a use case we support today neither with SAP badges nor with end-user badges, they are all nominative and then cannot be reassigned.

**Comment by mahdibenromdhane** [comment] 2020-10-27 11:12
Tags With only anonymous sessions (userID null) can be:
- Reassigned to another user and a popup should show to ask if we want to assign the orphan sessions to the new user: 
![image](https://user-images.githubusercontent.com/33232018/97293399-e7c59980-184c-11eb-9158-a376d4a95980.png)

- Deleted

- If deleted and then create a tag with the same ID a popup should show to ask if we want to assign the orphan sessions to the user assigned to the new tag. 
![image](https://user-images.githubusercontent.com/33232018/97293846-818d4680-184d-11eb-9c05-5f592db9b312.png)

**Comment by WillyLellouch** [comment] 2021-01-13 10:15
@mahdibenromdhane @jerome-benoit 

The functionality works as described in different contexts.
I had to go in the database to create Tags without users and sessions with those tags. Is it even possible to start sessions without a user ? When I tried to do so, it return an error, which I think is correct behaviour.

**Comment by LucasBrazi06** [comment] 2021-01-13 10:40
> @mahdibenromdhane @jerome-benoit
> 
> The functionality works as described in different contexts.
> I had to go in the database to create Tags without users and sessions with those tags. Is it even possible to start sessions without a user ? When I tried to do so, it returned an error, which I think is correct behaviour.

Yes you can start a session without a user when the access control is disabled in the Site Area:

![image](https://user-images.githubusercontent.com/25266945/104441463-03ab2280-5594-11eb-9816-68946f178d54.png)

**Comment by WillyLellouch** [comment] 2021-01-13 11:00
Ok I tried it that way and the functionality works as intended here too

**Comment by LucasBrazi06** [comment] 2021-01-13 11:17
Ok, then I'll close the issue.
Thanks!

**Closed by LucasBrazi06** 2021-01-13 11:17 UTC
Labels: bug, high-prio
